export enum Constants {
  ADD_BUDGET = 'ADD_BUDGET',
  REMOVE_BUDGET = 'REMOVE_BUDGET',
  EDIT_BUDGET = 'EDIT_BUDGET',
  CHANGE_TRANSACTIONS = 'CHANGE_TRANSACTIONS',
  REMOVE_BUDGET_ALL = 'REMOVE_BUDGET_ALL',
}
