export enum Constants {
  ADD_TRANSACTION = 'ADD_TRANSACTION',
  REMOVE_TRANSACTION = 'REMOVE_TRANSACTION',
  REMOVE_TRANSACTIONS_BUDGET = 'REMOVE_TRANSACTIONS_BUDGET',
  EDIT_TRANSACTION = 'EDIT_TRANSACTION',
}
